djf_surveys/admins/urls.py
from django.urls import path
from djf_surveys.admins import views as admin_views
from djf_surveys.admins.v2 import views as admin_views_v2
from djf_surveys.admins.views import DirectionsListView, DirectionUpdateView, DirectionDeleteView, DirectionAddView

urlpatterns = [
    path('', admin_views.AdminSurveyListView.as_view(), name='admin_survey'),
    path('create/survey/', admin_views.AdminCrateSurveyView.as_view(), name='admin_create_survey'),
    path('edit/survey/<str:slug>/', admin_views.AdminEditSurveyView.as_view(), name='admin_edit_survey'),
    path('delete/survey/<str:slug>/', admin_views.AdminDeleteSurveyView.as_view(), name='admin_delete_survey'),
    path('forms/<str:slug>/', admin_views.AdminSurveyFormView.as_view(), name='admin_forms_survey'),
    path('question/add/<int:pk>/<int:type_field>', admin_views_v2.AdminCreateQuestionView.as_view(),
         name='admin_create_question'),
    path('question/edit/<int:pk>/', admin_views_v2.AdminUpdateQuestionView.as_view(), name='admin_edit_question'),
    path('question/delete/<int:pk>/', admin_views.AdminDeleteQuestionView.as_view(), name='admin_delete_question'),
    path('question/ordering/', admin_views.AdminChangeOrderQuestionView.as_view(), name='admin_change_order_question'),
    path('download/survey/<str:slug>/', admin_views.DownloadResponseSurveyView.as_view(), name='admin_download_survey'),
    path('summary/survey/<str:slug>/', admin_views.SummaryResponseSurveyView.as_view(), name='admin_summary_survey'),
    path('directions/', DirectionsListView.as_view(), name='directions'),
    path('directions/add/', DirectionAddView.as_view(), name='add-direction'),
    path('directions/edit/<int:pk>/', DirectionUpdateView.as_view(), name='edit_direction'),
    path('directions/delete/<int:pk>/', DirectionDeleteView.as_view(), name='delete_direction'),
]

djf_surveys/urls.py
from django.urls import path, include
from djf_surveys import views
from djf_surveys.app_settings import SURVEYS_ADMIN_BASE_PATH

app_name = 'djf_surveys'
urlpatterns = [
    path('', views.SurveyListView.as_view(), name='index'),
    path('detail/<str:slug>/', views.DetailSurveyView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.EditSurveyFormView.as_view(), name='edit'),
    path('detail/result/<int:pk>/', views.DetailResultSurveyView.as_view(), name='detail_result'),
    path('create/<str:slug>/', views.CreateSurveyFormView.as_view(), name='create'),
    path('delete/<int:pk>/', views.DeleteSurveyAnswerView.as_view(), name='delete'),
    path('share/<str:slug>/', views.share_link, name='share_link'),
    path('success/<str:slug>/', views.SuccessPageSurveyView.as_view(), name='success'),
    path(SURVEYS_ADMIN_BASE_PATH, include('djf_surveys.admins.urls')),
]

moi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('moi-admin/', admin.site.urls),
    path('', include('djf_surveys.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djf_surveys/admins/v2/views.py
from django.utils.text import capfirst
from django.utils.translation import gettext, gettext_lazy as _
from django.views.generic.edit import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.http import Http404
from djf_surveys.app_settings import SURVEYS_ADMIN_BASE_PATH
from djf_surveys.models import Survey, Question, TYPE_FIELD, TYPE_FIELD_CHOICES
from djf_surveys.mixin import ContextTitleMixin
from djf_surveys.admins.v2.forms import QuestionForm, QuestionWithChoicesForm, QuestionFormRatings


@method_decorator(staff_member_required, name='dispatch')
class AdminCreateQuestionView(ContextTitleMixin, CreateView):
    template_name = 'djf_surveys/admins/question_form_v2.html'
    success_url = reverse_lazy("djf_surveys:")
    title_page = _("Savol kiritish")
    survey = None
    type_field_id = None

    def dispatch(self, request, *args, **kwargs):
        self.survey = get_object_or_404(Survey, id=kwargs['pk'])
        self.type_field_id = kwargs['type_field']
        if self.type_field_id not in TYPE_FIELD:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        choices = [TYPE_FIELD.multi_select, TYPE_FIELD.select, TYPE_FIELD.radio]
        if self.type_field_id in choices:
            return QuestionWithChoicesForm
        elif self.type_field_id == TYPE_FIELD.rating:
            return QuestionFormRatings
        else:
            return QuestionForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            question = form.save(commit=False)
            question.survey = self.survey
            question.type_field = self.type_field_id
            question.save()
            messages.success(self.request, gettext("%(page_action_name)s succeeded.") % dict(
                page_action_name=capfirst(self.title_page.lower())))
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_field_id'] = self.type_field_id
        return context

    def get_success_url(self):
        return reverse("djf_surveys:admin_forms_survey", args=[self.survey.slug])

    def get_sub_title_page(self):
        return gettext("Type Field %s") % dict(TYPE_FIELD_CHOICES).get(self.type_field_id, "Unknown")


@method_decorator(staff_member_required, name='dispatch')
class AdminUpdateQuestionView(ContextTitleMixin, UpdateView):
    model = Question
    template_name = 'djf_surveys/admins/question_form_v2.html'
    success_url = SURVEYS_ADMIN_BASE_PATH
    title_page = _("Savolni tahrirlash")
    survey = None
    type_field_id = None

    def dispatch(self, request, *args, **kwargs):
        question = self.get_object()
        self.type_field_id = question.type_field
        self.survey = question.survey
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        choices = [TYPE_FIELD.multi_select, TYPE_FIELD.select, TYPE_FIELD.radio]
        if self.type_field_id in choices:
            return QuestionWithChoicesForm
        elif self.type_field_id == TYPE_FIELD.rating:
            return QuestionFormRatings
        else:
            return QuestionForm

    def get_object(self):
        object = super(UpdateView, self).get_object(self.get_queryset())
        if object.type_field == TYPE_FIELD.rating:
            if not object.choices:  # use 5 as default for backward compatibility
                object.choices = 5
        return object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_field_id'] = self.type_field_id
        return context

    def get_success_url(self):
        return reverse("djf_surveys:admin_forms_survey", args=[self.survey.slug])

    def get_sub_title_page(self):
        question = self.get_object()
        return gettext("Type Field %s") % question.get_type_field_display()

djf_surveys/admins/views.py
import codecs
import csv
from io import StringIO
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import capfirst
from django.utils.translation import gettext, gettext_lazy as _
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.db.models import Avg
from accounts.models import Profile
from djf_surveys.app_settings import SURVEYS_ADMIN_BASE_PATH
from djf_surveys.models import Survey, Question, UserAnswer, Answer, Direction, UserRating
from djf_surveys.mixin import ContextTitleMixin
from djf_surveys.views import SurveyListView
from djf_surveys.forms import BaseSurveyForm
from djf_surveys.summary import SummaryResponse
from djf_surveys.admins.v2.forms import SurveyForm


@method_decorator(staff_member_required, name='dispatch')
class AdminCrateSurveyView(ContextTitleMixin, CreateView):
    template_name = 'djf_surveys/admins/form.html'
    form_class = SurveyForm
    title_page = _("Yangi so‘rovnoma qo‘shish")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            survey = form.save()
            self.success_url = reverse("djf_surveys:admin_forms_survey", args=[survey.slug])
            messages.success(self.request, gettext("%(page_action_name)s succeeded.") % dict(page_action_name=capfirst(self.title_page.lower())))
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@method_decorator(staff_member_required, name='dispatch')
class AdminEditSurveyView(ContextTitleMixin, UpdateView):
    model = Survey
    form_class = SurveyForm
    template_name = 'djf_surveys/admins/form.html'
    title_page = _("So‘rovnomani tahrirlash")

    def get_success_url(self):
        survey = self.get_object()
        return reverse("djf_surveys:admin_forms_survey", args=[survey.slug])


@method_decorator(staff_member_required, name='dispatch')
class AdminSurveyListView(SurveyListView):
    template_name = 'djf_surveys/admins/survey_list.html'


@method_decorator(staff_member_required, name='dispatch')
class AdminSurveyFormView(ContextTitleMixin, FormMixin, DetailView):
    model = Survey
    template_name = 'djf_surveys/admins/form_preview.html'
    form_class = BaseSurveyForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Existing context data...

        # Add eligible_users to context
        context['eligible_users'] = Profile.objects.filter(
            position__slug__in=[
                'boshligi', 'boshligi-orinbosari', 'professori', 'dotsenti',
                'katta-oqituvchisi', 'oqituvchisi', 'kabinet-boshligi'
            ]
        ).distinct()
        return context

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(survey=self.object, user=self.request.user, **self.get_form_kwargs())

    def get_title_page(self):
        return self.object.name

    def get_sub_title_page(self):
        return self.object.description

    def dispatch(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'POST':
            return self.handle_ajax_request(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    def handle_ajax_request(self, request, *args, **kwargs):
        user_id = request.POST.get('user_id')
        can_be_rated = request.POST.get('can_be_rated') == 'true'

        try:
            profile = Profile.objects.get(id=user_id)
            profile.can_be_rated = can_be_rated
            profile.save()
            return JsonResponse({'status': 'success', 'can_be_rated': profile.can_be_rated})
        except Profile.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Foydalanuvchi topilmadi.'}, status=404)


@method_decorator(staff_member_required, name='dispatch')
class AdminDeleteSurveyView(DetailView):
    model = Survey

    def get(self, request, *args, **kwargs):
        survey = self.get_object()
        survey.delete()
        messages.success(request, gettext("So‘rovnoma %ss muvaffaqiyatli o‘chirildi.") % survey.name)
        return redirect("djf_surveys:admin_survey")


@method_decorator(staff_member_required, name='dispatch')
class AdminCreateQuestionView(ContextTitleMixin, CreateView):
    """
    Note: This class already has version 2
    """
    model = Question
    template_name = 'djf_surveys/admins/question_form.html'
    success_url = reverse_lazy("djf_surveys:")
    fields = ['label', 'key', 'type_field', 'choices', 'help_text', 'required']
    title_page = _("Savol qo‘shish")
    survey = None

    def dispatch(self, request, *args, **kwargs):
        self.survey = get_object_or_404(Survey, id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            question = form.save(commit=False)
            question.survey = self.survey
            question.save()
            messages.success(self.request, gettext("%(page_action_name)s bajarildi.") % dict(page_action_name=capfirst(self.title_page.lower())))
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse("djf_surveys:admin_forms_survey", args=[self.survey.slug])


@method_decorator(staff_member_required, name='dispatch')
class AdminUpdateQuestionView(ContextTitleMixin, UpdateView):
    """
    Note: This class already has version 2
    """
    model = Question
    template_name = 'djf_surveys/admins/question_form.html'
    success_url = SURVEYS_ADMIN_BASE_PATH
    fields = ['label', 'key', 'type_field', 'choices', 'help_text', 'required']
    title_page = _("Savol qo‘shish")
    survey = None

    def dispatch(self, request, *args, **kwargs):
        question = self.get_object()
        self.survey = question.survey
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("djf_surveys:admin_forms_survey", args=[self.survey.slug])


@method_decorator(staff_member_required, name='dispatch')
class AdminDeleteQuestionView(DetailView):
    model = Question
    survey = None

    def dispatch(self, request, *args, **kwargs):
        question = self.get_object()
        self.survey = question.survey
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        question = self.get_object()
        question.delete()
        messages.success(request, gettext("Savol %ss muvaffaqiyatli o‘chirildi.") % question.label)
        return redirect("djf_surveys:admin_forms_survey", slug=self.survey.slug)


@method_decorator(staff_member_required, name='dispatch')
class AdminChangeOrderQuestionView(View):
    def post(self, request, *args, **kwargs):
        ordering = request.POST['order_question'].split(",")
        for index, question_id in enumerate(ordering):
            if question_id:
                question = Question.objects.get(id=question_id)
                question.ordering = index
                question.save()

        data = {
            'message': gettext("Update ordering of questions succeeded.")
        }
        return JsonResponse(data, status=200)


@method_decorator(staff_member_required, name='dispatch')
class DownloadResponseSurveyView(DetailView):
    model = Survey

    def get(self, request, *args, **kwargs):
        survey = self.get_object()
        user_answers = UserAnswer.objects.filter(survey=survey)
        csv_buffer = StringIO()
        csv_buffer.write(codecs.BOM_UTF8.decode('utf-8'))

        writer = csv.writer(csv_buffer, delimiter=',')

        rows = []
        header = []
        for index, user_answer in enumerate(user_answers):
            if index == 0:
                header.append('foydalanuvchi')
                header.append('yuborilgan vaqti')
                header.append('kurs nomi')

            rows.append(user_answer.user.username if user_answer.user else 'ro‘yxatdan o‘tmagan')
            rows.append(user_answer.updated_at.strftime("%Y-%m-%d %H:%M:%S"))
            rows.append(user_answer.direction.name if user_answer.direction else 'yo‘nalish tanlanmagan')

            for answer in user_answer.answer_set.order_by('question__id'):
                if index == 0:
                    header.append(answer.question.label)
                rows.append(answer.get_value_for_csv)

            if index == 0:
                writer.writerow(header)
            writer.writerow(rows)
            rows = []

        response = HttpResponse(content_type='text/csv; charset=utf-8')
        response['Content-Disposition'] = f'attachment; filename={survey.slug}.csv'
        response.write(csv_buffer.getvalue())
        return response


@method_decorator(staff_member_required, name='dispatch')
class SummaryResponseSurveyView(ContextTitleMixin, DetailView):
    model = Survey
    template_name = "djf_surveys/admins/summary.html"
    title_page = _("Natija")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        survey = self.get_object()

        current_year = now().year
        selected_year = self.request.GET.get('year', None)
        try:

djf_surveys/templates/djf_surveys/admins/add_direction.html
{% extends "djf_surveys/master.html" %}
{% block title %}Yangi kurs qo‘shish{% endblock title %}
{% block content %}
<div class="max-w-md mx-auto mt-10 bg-white p-8 rounded shadow">
    <h2 class="text-2xl font-semibold mb-6 text-center">Yangi kurs qo‘shish</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="flex justify-center space-x-4 mt-4">
            <button type="submit" class="bg-blue-600 text-white py-2 px-4 rounded hover:bg-blue-700">
                Saqlash
            </button>
            <a href="{% url 'djf_surveys:directions' %}" class="bg-gray-300 text-gray-700 py-2 px-4 rounded hover:bg-gray-400">
                Bekor qilish
            </a>
        </div>
    </form>
</div>
{% endblock content %}

djf_surveys/templates/djf_surveys/admins/direction_delete.html
{% extends "djf_surveys/master.html" %}
{% block title %}Kursni o‘chirish{% endblock title %}
{% block content %}
<div class="max-w-md mx-auto mt-10 bg-white p-8 rounded shadow text-center">
    <h2 class="text-2xl font-semibold mb-6">Kursni o‘chirish</h2>
    <p class="mb-6">
        <strong>{{ object.name }}</strong> nomli kursni o‘chirmoqchimisiz?
    </p>
    <form method="post" class="flex justify-center space-x-4">
        {% csrf_token %}
        <button type="submit" class="bg-red-600 text-white py-2 px-4 rounded hover:bg-red-700">
            Ha, o‘chirish
        </button>
        <a href="{% url 'djf_surveys:directions' %}" class="bg-gray-300 text-gray-700 py-2 px-4 rounded hover:bg-gray-400">
            Bekor qilish
        </a>
    </form>
</div>
{% endblock content %}

djf_surveys/templates/djf_surveys/admins/form_preview.html
{% extends 'djf_surveys/master.html' %}
{% load djf_survey_tags static i18n %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'djf_surveys/css/rating.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .user-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 8px;
            border-bottom: 1px solid #e2e8f0;
        }
        .user-name {
            font-size: 16px;
        }
        .toggle-switch {
            position: relative;
            display: inline-block;
            width: 50px;
            height: 24px;
        }
        .toggle-switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            transition: .4s;
            border-radius: 24px;
        }
        .slider:before {
            position: absolute;
            content: "";
            height: 18px;
            width: 18px;
            left: 3px;
            bottom: 3px;
            background-color: white;
            transition: .4s;
            border-radius: 50%;
        }
        input:checked + .slider {
            background-color: #4ade80;
        }
        input:checked + .slider:before {
            transform: translateX(26px);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="flex py-1 fixed bottom-10 right-10">
        <button
            class="z-20 block p-4 text-blue-100 transition-all bg-blue-700 border-2 border-white rounded-full active:bg-purple-50 hover:scale-110 focus:outline-none focus:ring"
            data-te-toggle="modal"
            data-te-target="#addQuestion"
            data-te-ripple-init
            data-te-ripple-color="light"
            type="button">
            {% include "djf_surveys/buttons/add_button.html" with size=6 %}
            <span class="items-center float-right"> {% trans 'Savol qo‘shish' %} </span>
        </button>
    </div>

    <div class="max-w-screen-xl px-4 py-16 mx-auto sm:px-6 lg:px-8">
        <div class="max-w-lg mx-auto">
            <div class="flex -space-x-4 hover:space-x-1 py-1 float-right">
                <a href="{% url 'djf_surveys:admin_edit_survey' object.slug %}"
                   class="z-20 block p-4 text-blue-700 transition-all bg-blue-100 border-2 border-white rounded-full active:bg-blue-50 hover:scale-110 focus:outline-none focus:ring"
                   type="button">
                    {% include "djf_surveys/buttons/edit_button.html" %}
                </a>
                <a href="#" class="button-share z-20 block p-4 text-amber-700 transition-all bg-amber-100 border-2 border-white rounded-full active:bg-amber-50 hover:scale-110 focus:outline-none focus:ring"
                    type="button" data-share-link="{% url 'djf_surveys:share_link' object.slug %}">
                    {% include "djf_surveys/buttons/share_button.html" %}
                </a>
                <a class="button-delete z-30 block p-4 text-red-700 transition-all bg-red-100 border-2 border-white rounded-full hover:scale-110 focus:outline-none focus:ring active:bg-red-50"
                   data-te-toggle="modal"
                   data-te-target="#modalDelete"
                   data-mdb-object_name="{{ object.name }}"
                   data-mdb-object_delete_url="{% url 'djf_surveys:admin_delete_survey' object.slug %}">
                    {% include "djf_surveys/buttons/delete_button.html" %}
                </a>
            </div>
            <h1 class="text-2xl font-bold text-center text-blue-500 sm:text-3xl">{{ title_page }}</h1>

            <p class="max-w-md mx-auto mt-4 text-center text-gray-500">
                {{ sub_title_page }}
            </p>

            <form method="post" class="mx-auto mt-12" id="sortable">
                {% csrf_token %}
                {% for field in form %}
                    <div class="ui-state-default" id="{{ field|get_id_field }}">
                        <div class="flex -space-x-4 hover:space-x-1 py-1">
                            <a href="{% url 'djf_surveys:admin_edit_question' field|get_id_field  %}"
                               class="z-20 block p-4 text-blue-700 transition-all bg-blue-100 border-2 border-white rounded-full active:bg-blue-50 hover:scale-110 focus:outline-none focus:ring"
                               type="button">
                                {% include "djf_surveys/buttons/edit_button.html" %}
                            </a>

                            <a class="button-delete z-30 block p-4 text-red-700 transition-all bg-red-100 border-2 border-white rounded-full hover:scale-110 focus:outline-none focus:ring active:bg-red-50"
                               data-te-toggle="modal"
                               data-te-target="#modalDelete"
                               data-mdb-object_name="{{ field.label }}"
                               data-mdb-object_delete_url="{% url 'djf_surveys:admin_delete_question' field|get_id_field %}">
                                {% include "djf_surveys/buttons/delete_button.html" %}
                            </a>

                        </div>

                        <a href="#"
                           class="float-right z-30 block p-2 m-2 text-gray-500 transition-all bg-gray-100 border-2 border-white rounded-full hover:scale-110 focus:outline-none focus:ring active:bg-red-50">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                      d="M7 11.5V14m0-2.5v-6a1.5 1.5 0 113 0m-3 6a1.5 1.5 0 00-3 0v2a7.5 7.5 0 0015 0v-5a1.5 1.5 0 00-3 0m-6-3V11m0-5.5v-1a1.5 1.5 0 013 0v1m0 0V11m0-5.5a1.5 1.5 0 013 0v3m0 0V11"/>
                            </svg>
                        </a>
                        <div class="p-8 mb-6 rounded-lg shadow-md border border-gray-200 bg-white">
                            <label for="email" class="text-lg font-medium">{{ field.label }}</label>

                            <div class="mt-1">
                                {% if field.field.widget.input_type == 'radio' or field.field.widget.input_type == 'checkbox' %}
                                    {{ field }}
                                {% else %}
                                    {{ field|addclass:'w-full p-4 pr-12 text-sm border-gray-500 rounded-lg shadow-sm' }}
                                {% endif %}
                            </div>
                            <p class="text-xs text-gray-400 mt-2">{{ field.help_text }}</p>
                        </div>
                    </div>

                {% endfor %}
            </form>
        </div>

        {% include 'djf_surveys/components/modal_delete.html' %}
        {% include 'djf_surveys/components/modal_choice_field_type.html' %}
    </div>

    <div class="max-w-screen-xl px-4 py-16 mx-auto sm:px-6 lg:px-8">
        <div class="max-w-lg mx-auto">
            <!-- Existing content... -->

            <h2 class="text-xl font-semibold mb-4">Baholanadigan professor-o‘qituvchilar ro‘yxati</h2>
            <div class="bg-white shadow overflow-hidden sm:rounded-md">
                <ul class="divide-y divide-gray-200">
                    {% for user in eligible_users %}
                        <li class="user-row">
                            <span class="user-name">{{ user.rank }} {{ user.user.last_name }} {{ user.user.first_name }}</span>
                            <label class="toggle-switch">
                                <input type="checkbox" class="can-be-rated-checkbox" data-user-id="{{ user.id }}" {% if user.can_be_rated %}checked{% endif %}>
                                <span class="slider"></span>
                            </label>
                        </li>
                    {% empty %}
                        <li class="px-6 py-4">Foydalanuvchilar topilmadi!</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <!-- Existing modals... -->
    </div>



{% endblock %}

{% block extra_js %}
    <script src="https://code.jquery.com/jquery-3.6.1.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#sortable").sortable({
                opacity: 0.7,
                update: function (event, ui) {
                    const order = $(this).sortable('toArray');
                    console.log(order);
                    $.ajax({
                        url: "{% url 'djf_surveys:admin_change_order_question' %}",
                        type: 'POST',
                        headers: {"X-CSRFToken": '{{csrf_token}}'},
                        data: {
                            'order_question': order.toString(),
                        },
                        dataType: 'json',
                        success: function (data) {
                            console.log(data.message);
                        },
                        error: function (data) {
                            alert("{% trans 'Xatolik sodir bo‘ldi!' %}");
                        }
                    });
                }
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            // Handle sortable if needed
            $("#sortable").sortable({
                opacity: 0.7,
                update: function (event, ui) {
                    const order = $(this).sortable('toArray');
                    console.log(order);
                    $.ajax({
                        url: "{% url 'djf_surveys:admin_change_order_question' %}",
                        type: 'POST',
                        headers: {"X-CSRFToken": '{{ csrf_token }}'},
                        data: {
                            'order_question': order.toString(),
                        },
                        dataType: 'json',
                        success: function (data) {
                            console.log(data.message);
                        },
                        error: function (data) {
                            alert("{% trans 'Xatolik sodir bo‘ldi!' %}");
                        }
                    });
                }
            });

            // Handle checkbox toggle
            $('.can-be-rated-checkbox').change(function() {
                const userId = $(this).data('user-id');
                const canBeRated = $(this).is(':checked');

                $.ajax({
                    url: window.location.href,  // Current URL
                    type: 'POST',
                    headers: {"X-CSRFToken": '{{ csrf_token }}'},
                    data: {
                        'user_id': userId,
                        'can_be_rated': canBeRated,
                    },
                    dataType: 'json',
                    success: function(response) {
                        if(response.status === 'success') {
                            console.log(`Foydalanuvchi ${userId} baholanishi mumkin: ${response.can_be_rated}`);
                        } else {
                            alert(response.message);
                        }
                    },
                    error: function(xhr, status, error) {
                        alert("{% trans 'Foydalanuvchi holatini yangilashda xato sodir bo‘ldi.' %}");
                        // Optionally, revert the checkbox state
                        location.reload();
                    }
                });
            });
        });
    </script>

    {% include 'djf_surveys/components/modal_delete_js.html' %}
    {% include 'djf_surveys/components/share_link_button_js.html' %}
{% endblock %}

djf_surveys/templates/djf_surveys/admins/question_form_v2.html
{% extends 'djf_surveys/admins/form.html' %}