accounts/urls.py
from django.urls import path
from .views import (profile, CustomLoginView, RegisterView,
                    CustomLogoutView, UsersListView, edit_profile, UserDeleteView)
from .forms import UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='accounts/login.html',
                                           authentication_form=UserLoginForm),
         name='login'),
    path('logout/', CustomLogoutView.as_view(next_page='/'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    # Hozirgi "shaxsiy" profil
    path('profile/', profile, name='profile'),

    # Barcha userlarning ro'yxati
    path('users_list/', UsersListView.as_view(), name='users_list'),

    # Tahrirlash — <user_id> bilan
    path('profile/<int:pk>/', edit_profile, name='edit_profile'),

    # O'chirish
    path('delete_user/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
]

djf_surveys/admins/urls.py
from django.urls import path
from djf_surveys.admins import views as admin_views
from djf_surveys.admins.v2 import views as admin_views_v2
from djf_surveys.admins.views import DirectionsListView, DirectionUpdateView, DirectionDeleteView, DirectionAddView

urlpatterns = [
    path('', admin_views.AdminSurveyListView.as_view(), name='admin_survey'),
    path('create/survey/', admin_views.AdminCrateSurveyView.as_view(), name='admin_create_survey'),
    path('edit/survey/<str:slug>/', admin_views.AdminEditSurveyView.as_view(), name='admin_edit_survey'),
    path('delete/survey/<str:slug>/', admin_views.AdminDeleteSurveyView.as_view(), name='admin_delete_survey'),
    path('forms/<str:slug>/', admin_views.AdminSurveyFormView.as_view(), name='admin_forms_survey'),
    path('question/add/<int:pk>/<int:type_field>', admin_views_v2.AdminCreateQuestionView.as_view(),
         name='admin_create_question'),
    path('question/edit/<int:pk>/', admin_views_v2.AdminUpdateQuestionView.as_view(), name='admin_edit_question'),
    path('question/delete/<int:pk>/', admin_views.AdminDeleteQuestionView.as_view(), name='admin_delete_question'),
    path('question/ordering/', admin_views.AdminChangeOrderQuestionView.as_view(), name='admin_change_order_question'),
    path('download/survey/<str:slug>/', admin_views.DownloadResponseSurveyView.as_view(), name='admin_download_survey'),
    path('summary/survey/<str:slug>/', admin_views.SummaryResponseSurveyView.as_view(), name='admin_summary_survey'),
    path('directions/', DirectionsListView.as_view(), name='directions'),
    path('directions/add/', DirectionAddView.as_view(), name='add-direction'),
    path('directions/edit/<int:pk>/', DirectionUpdateView.as_view(), name='edit_direction'),
    path('directions/delete/<int:pk>/', DirectionDeleteView.as_view(), name='delete_direction'),
]

djf_surveys/urls.py
from django.urls import path, include
from djf_surveys import views
from djf_surveys.app_settings import SURVEYS_ADMIN_BASE_PATH

app_name = 'djf_surveys'
urlpatterns = [
    path('', views.SurveyListView.as_view(), name='index'),
    path('detail/<str:slug>/', views.DetailSurveyView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.EditSurveyFormView.as_view(), name='edit'),
    path('detail/result/<int:pk>/', views.DetailResultSurveyView.as_view(), name='detail_result'),
    path('create/<str:slug>/', views.CreateSurveyFormView.as_view(), name='create'),
    path('delete/<int:pk>/', views.DeleteSurveyAnswerView.as_view(), name='delete'),
    path('share/<str:slug>/', views.share_link, name='share_link'),
    path('success/<str:slug>/', views.SuccessPageSurveyView.as_view(), name='success'),
    path(SURVEYS_ADMIN_BASE_PATH, include('djf_surveys.admins.urls')),
]

moi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('moi-admin/', admin.site.urls),
    path('', include('djf_surveys.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djf_surveys/admins/v2/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from djf_surveys.models import Question, Survey
from djf_surveys.widgets import InlineChoiceField


class QuestionForm(forms.ModelForm):
    
    class Meta:
        model = Question
        fields = ['label', 'key', 'help_text', 'required']


class QuestionWithChoicesForm(forms.ModelForm):
    
    class Meta:
        model = Question
        fields = ['label', 'key', 'choices', 'help_text', 'required']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['choices'].widget = InlineChoiceField()
        self.fields['choices'].help_text = _("Yana variant qo'shish uchun + tugmasini bosing")


class QuestionFormRatings(forms.ModelForm):
    
    class Meta:
        model = Question
        fields = ['label', 'key', 'choices', 'help_text', 'required']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['choices'].widget = forms.NumberInput(attrs={'max': 10, 'min': 1})
        self.fields['choices'].help_text = _("1 va 10 orasida bo‘lishi kerak")
        self.fields['choices'].label = _("Reytinglar soni")
        self.fields['choices'].initial = 5


class SurveyForm(forms.ModelForm):
    
    class Meta:
        model = Survey
        fields = [
            'name', 'description', 'editable', 'deletable', 
            'duplicate_entry', 'private_response', 'can_anonymous_user',
            'notification_to', 'success_page_content'
        ]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['notification_to'].widget = InlineChoiceField()

djf_surveys/admins/v2/views.py
from django.utils.text import capfirst
from django.utils.translation import gettext, gettext_lazy as _
from django.views.generic.edit import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.http import Http404
from djf_surveys.app_settings import SURVEYS_ADMIN_BASE_PATH
from djf_surveys.models import Survey, Question, TYPE_FIELD, TYPE_FIELD_CHOICES
from djf_surveys.mixin import ContextTitleMixin
from djf_surveys.admins.v2.forms import QuestionForm, QuestionWithChoicesForm, QuestionFormRatings


@method_decorator(staff_member_required, name='dispatch')
class AdminCreateQuestionView(ContextTitleMixin, CreateView):
    template_name = 'djf_surveys/admins/question_form_v2.html'
    success_url = reverse_lazy("djf_surveys:")
    title_page = _("Savol kiritish")
    survey = None
    type_field_id = None

    def dispatch(self, request, *args, **kwargs):
        self.survey = get_object_or_404(Survey, id=kwargs['pk'])
        self.type_field_id = kwargs['type_field']
        if self.type_field_id not in TYPE_FIELD:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        choices = [TYPE_FIELD.multi_select, TYPE_FIELD.select, TYPE_FIELD.radio]
        if self.type_field_id in choices:
            return QuestionWithChoicesForm
        elif self.type_field_id == TYPE_FIELD.rating:
            return QuestionFormRatings
        else:
            return QuestionForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            question = form.save(commit=False)
            question.survey = self.survey
            question.type_field = self.type_field_id
            question.save()
            messages.success(self.request, gettext("%(page_action_name)s succeeded.") % dict(
                page_action_name=capfirst(self.title_page.lower())))
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_field_id'] = self.type_field_id
        return context

    def get_success_url(self):
        return reverse("djf_surveys:admin_forms_survey", args=[self.survey.slug])

    def get_sub_title_page(self):
        return gettext("Type Field %s") % dict(TYPE_FIELD_CHOICES).get(self.type_field_id, "Unknown")


@method_decorator(staff_member_required, name='dispatch')
class AdminUpdateQuestionView(ContextTitleMixin, UpdateView):
    model = Question
    template_name = 'djf_surveys/admins/question_form_v2.html'
    success_url = SURVEYS_ADMIN_BASE_PATH
    title_page = _("Savolni tahrirlash")
    survey = None
    type_field_id = None

    def dispatch(self, request, *args, **kwargs):
        question = self.get_object()
        self.type_field_id = question.type_field
        self.survey = question.survey
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        choices = [TYPE_FIELD.multi_select, TYPE_FIELD.select, TYPE_FIELD.radio]
        if self.type_field_id in choices:
            return QuestionWithChoicesForm
        elif self.type_field_id == TYPE_FIELD.rating:
            return QuestionFormRatings
        else:
            return QuestionForm

    def get_object(self):
        object = super(UpdateView, self).get_object(self.get_queryset())
        if object.type_field == TYPE_FIELD.rating:
            if not object.choices:  # use 5 as default for backward compatibility
                object.choices = 5
        return object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_field_id'] = self.type_field_id
        return context

    def get_success_url(self):
        return reverse("djf_surveys:admin_forms_survey", args=[self.survey.slug])

    def get_sub_title_page(self):
        question = self.get_object()
        return gettext("Type Field %s") % question.get_type_field_display()

djf_surveys/templates/djf_surveys/answer_list.html
{% extends get_master_template %}
{% load i18n static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'djf_surveys/te-starter/css/tw-elements.min.css' %}">
    <link rel="stylesheet" href="{% static 'djf_surveys/css/rating.css' %}"/>
{% endblock %}

{% block content %}
    <div class="container px-5 py-5">
        <section>
            <div class="py-16 lg:items-end lg:justify-between lg:flex sm:px-6 lg:px-8">
                <h2 class="max-w-xl text-2xl font-bold sm:text-3xl">
                    {% trans "Natija" %} - {{ object.name }}
                </h2>

                <div class="btn-group">
                    <div class="flex -space-x-4 hover:space-x-1 float-right">
                        {% if user.is_superuser %}
                            <a href="{% url 'djf_surveys:admin_download_survey' survey.slug %}"
                               class="z-20 block p-4 text-purple-700 transition-all bg-purple-100 border-2 border-white rounded-full active:bg-purple-50 hover:scale-110 focus:outline-none focus:ring"
                               type="button">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
                                </svg>
                            </a>

                            <a href="{% url 'djf_surveys:admin_summary_survey' survey.slug %}"
                               class="z-20 block p-4 text-blue-700 transition-all bg-blue-100 border-2 border-white rounded-full active:bg-blue-50 hover:scale-110 focus:outline-none focus:ring"
                               type="button">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"/>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"/>
                                </svg>
                            </a>
                        {% endif %}
                        <a href="{% url 'djf_surveys:create' survey.slug %}"
                           class="z-20 block p-4 text-green-700 transition-all bg-green-100 border-2 border-white rounded-full active:bg-green-50 hover:scale-110 focus:outline-none focus:ring"
                           type="button">
                            {% include "djf_surveys/buttons/add_button.html" %}
                        </a>
                        <a href="#"
                           class="button-share z-20 block p-4 text-amber-700 transition-all bg-amber-100 border-2 border-white rounded-full active:bg-amber-50 hover:scale-110 focus:outline-none focus:ring"
                           type="button" data-share-link="{% url 'djf_surveys:share_link' survey.slug %}">
                            {% include "djf_surveys/buttons/share_button.html" %}
                        </a>
                    </div>
                </div>
            </div>
        </section>

        {% if page_obj %}
            <div class="grid xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {% for object in page_obj %}
                    {% include 'djf_surveys/components/card_list_answer.html' %}
                {% endfor %}
            </div>
            <div class="py-10">
                {% include 'djf_surveys/components/pagination.html' %}
            </div>
        {% else %}
            {% include 'djf_surveys/components/empty_state.html' %}
        {% endif %}
    </div>

    {% include 'djf_surveys/components/modal_delete.html' %}

{% endblock %}

{% block extra_js %}
    <script src="{% static 'djf_surveys/te-starter/js/tw-elements.umd.min.js' %}"></script>
    {% include 'djf_surveys/components/modal_delete_js.html' %}
    {% include 'djf_surveys/components/share_link_button_js.html' %}
{% endblock %}

djf_surveys/templates/djf_surveys/detail_result.html
{% extends get_master_template %}
{% load djf_survey_tags static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'djf_surveys/te-starter/css/tw-elements.min.css' %}">
    <link rel="stylesheet" href="{% static 'djf_surveys/css/rating.css' %}"/>
{% endblock %}

{% block content %}
    <div class="max-w-screen-xl px-4 py-16 mx-auto sm:px-6 lg:px-8">
        <div class="max-w-lg mx-auto">
            <h1 class="text-2xl font-bold text-center text-blue-500 sm:text-3xl">{{ title_page }}</h1>

            <p class="max-w-md mx-auto mt-4 mb-4 text-center text-gray-500">
                {{ sub_title_page }}
            </p>

            {% include 'djf_surveys/components/card_list_answer.html' %}
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="{% static 'djf_surveys/te-starter/js/tw-elements.umd.min.js' %}"></script>
{% endblock %}

djf_surveys/templates/djf_surveys/master.html
<!doctype html>
{% load i18n static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'djf_surveys/te-starter/css/tw-elements.min.css' %}">
    <script src="{% static 'djf_surveys/css/tailwindcss-3.3.1.js' %}"></script>
    <script src="{% static 'djf_surveys/css/tailwindcss-plugin-3.3.1.js' %}"></script>
    <script src="{% static 'djf_surveys/js/cdn.min.js' %}"></script>
{#    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>#}

    {% block extra_css %}{% endblock %}
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            {% include 'djf_surveys/components/alert.html' %}
        {% endfor %}
    {% endif %}


    <nav class="bg-sky-100 border-gray-200 dark:bg-gray-900 text-xl" x-data="{ open: false }">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-2">
      <a href="{% url 'djf_surveys:index' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
          <img src="{% static 'djf_surveys/images/MOI.png' %}" class="h-[100px]" alt="IIV Malaka oshirish instituti" />
          <span class="self-center font-semibold whitespace-nowrap md:hover:text-blue-700 md:dark:hover:text-blue-500">IIV Malaka oshirish instituti</span>
      </a>
      <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
          <!-- Dropdown konteyneri -->
          <div class="relative inline-block text-left">
              <!-- Dropdown tugmasi -->
              <button type="button" class="flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-4 py-2" id="menu-button" aria-expanded="false" aria-haspopup="true" onclick="toggleDropdown()">
                {% if user.is_authenticated %}
                  {{ user.username }}
                {% else %}
                  Anonim
                {% endif %}
                <!-- Dropdown uchun pastga o'q ikonkasi -->
                <svg class="ml-2 w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
              </button>

              <!-- Dropdown menyusi -->
              <div id="dropdown-menu" class="absolute right-0 mt-2 w-full bg-white rounded-md shadow-lg py-1 z-20 hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-button">
                  <a href="{% url 'accounts:login' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Login</a>
                  <a href="{% url 'accounts:logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Chiqish</a>
              </div>
            </div>
          <button @click="open = !open" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
              <span class="sr-only">Menyu</span>
              <!-- Hamburger Icon -->
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
          </button>
      </div>
        <div :class="{'block': open, 'hidden': !open}" class="items-center justify-between w-full md:flex md:w-auto md:order-1" id="navbar-cta">
          <ul class="flex flex-col font-medium p-2 md:p-0 mt-4 border border-gray-100 rounded-lg md:space-x-4 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0">
            <li>
              <a href="{% url 'djf_surveys:index' %}" class="block py-2 px-2 md:p-0 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:dark:text-blue-500" aria-current="page">Bosh sahifa</a>
            </li>
            {% if user.is_staff %}
            <li>
              <a href="{% url 'djf_surveys:directions' %}" class="block py-2 px-2 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Kurslar</a>
            </li>
            <li>
              <a href="{% url 'accounts:users_list' %}" class="block py-2 px-2 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">O‘qituvchilar ro‘yxati</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mx-auto">
        {% block content %} {% endblock %}
    </div>
    <script src="{% static 'djf_surveys/te-starter/js/tw-elements.umd.min.js' %}"></script>
    {% include 'djf_surveys/components/alert_js.html' %}
    {% block extra_js %}{% endblock %}

<script>
  function toggleDropdown() {
    const dropdown = document.getElementById('dropdown-menu');
    dropdown.classList.toggle('hidden');
  }

  // Dropdown tashqarisiga bosilganda yopish
  window.onclick = function(event) {
    if (!event.target.matches('#menu-button') && !event.target.closest('#dropdown-menu')) {
      const dropdown = document.getElementById('dropdown-menu');
      if (!dropdown.classList.contains('hidden')) {
        dropdown.classList.add('hidden');
      }
    }
  }
</script>
</body>
</html>

djf_surveys/templates/djf_surveys/success-page.html
{% extends get_master_template %}
{% load static i18n %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'djf_surveys/te-starter/css/tw-elements.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container px-5 lg:py-32 sm:py-16">
        <div class="relative p-8 text-center border border-gray-200 rounded-lg">
            <div class="flex justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100" height="100" viewBox="0 0 48 48">
                    <path fill="#4caf50" d="M44,24c0,11.045-8.955,20-20,20S4,35.045,4,24S12.955,4,24,4S44,12.955,44,24z"></path><path fill="#ccff90" d="M34.602,14.602L21,28.199l-5.602-5.598l-2.797,2.797L21,33.801l16.398-16.402L34.602,14.602z"></path>
                    </svg>
            </div>
            <h1 class="text-3xl pb-6 font-medium">
               {% trans "Ushbu so‘rovnomani to‘ldirganingiz uchun tashakkur" %}
            </h1>
            <p class="mt-4 text-sm text-gray-500">
                {% if object.success_page_content %}
                    {{ object.success_page_content|safe }}
                {% else %}
                    {% trans "Sizning sa'y-harakatlaringiz va so'rovnomani to'ldirishga ajratgan vaqtingizni juda qadrlaymiz. Sizning javoblaringiz bizga yordam beradi." %}
                {% endif %}
            </p>

            <div class="flex justify-center py-6">
                <a href="{{ link_back_on_success_page }}" class="block mt-5 px-5 py-3 text-sm font-medium text-white bg-blue-500 rounded-lg">
                    {% trans "Ortga" %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

djf_surveys/templates/djf_surveys/survey_list.html
{% extends get_master_template %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'djf_surveys/te-starter/css/tw-elements.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container px-5 py-5">
        {% include 'djf_surveys/components/section_welcome.html' %}

        {% if user.is_authenticated and user.is_staff %}
        <section>
            <div class="py-6 flex items-center m-2">
                <h2 class="max-w-xl text-xl font-bold sm:text-xl">
                    Yangi anketa-so‘rovnoma yaratish
                </h2>

                <a href="{% url 'djf_surveys:admin_create_survey' %}" class="inline-block px-5 py-3 font-medium text-white bg-blue-500 rounded-lg ml-4">
                    {% include "djf_surveys/buttons/add_button.html" %}
                </a>
            </div>
        </section>
        {% endif %}

        {% include 'djf_surveys/components/search_form.html' %}
        {% if object_list %}
            <div class="grid xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2 gap-4">
                {% for survey in page_obj %}
                    {% include 'djf_surveys/components/card_list_survey.html' %}
                {% endfor %}
            </div>
            <div class="py-10">
                {% include 'djf_surveys/components/pagination.html' %}
            </div>
        {% else %}
            {% include 'djf_surveys/components/empty_state.html' %}
        {% endif %}
    </div>

    {% include 'djf_surveys/components/modal_delete.html' %}

{% endblock %}

{% block extra_js %}
    <script src="{% static 'djf_surveys/te-starter/js/tw-elements.umd.min.js' %}"></script>
    {% include 'djf_surveys/components/modal_delete_js.html' %}
{% endblock %}